pages:
  image: node
  script:
    - yarn --frozen-lockfile
    - yarn docs
    - rm -rf public
    - mv docs public
    - mv images public/
  artifacts:
    paths:
      - public
  only:
    - master
